# ----- Standard plugin features

# Show the death messages on the server
show-deathnotify: 'true'

# Allow players to access the deathtp command
allow-deathtp: 'true'

# Death Logs
allow-deathlog: 'true'

# Show kill or death streaks read in from killstreak.txt and deathstreak.txt
show-streaks: 'true'

# Push kill sounds to Spoutcraft clients
play-sounds: 'true'

# Item ID of the item you must have in your hand to teleport. Will remove 1 of these when the command is given. Leave 0 for free teleports.
charge-item: 0

# Show sign tombstones upon death
show-sign: 'false'

# Economy
deathtp-cost: 10

# CraftIRC
deathtp-tag: 'all'

# Allow World Travel = yes, no, permissions
allow-worldtravel: 'no'

# Window of time (in milliseconds) to count kills towards a multikill
multikill-timewindow: 5000

# ----- Death Messages

# Output how many of each death message was loaded into the server.log
verbose: 'false'

# Must contain at least 1 line. If there are more, it will appear randomly when a person dies.
# %n for player who died
# %a name of player who attacked in pvp deaths
# %i for item a player was using to kill someone else
#
# Colors
#
# &0 Black
# &1 Navy
# &2 Green
# &3 Blue
# &4 Red
# &5 Purple
# &6 Gold
# &7 LightGray
# &8 Gray
# &9 DarkPurple
# &a LightGreen
# &b LightBlue
# &c Rose
# &d LightPurple
# &e Yellow
# &f White

fall:
- '&5%n&7 tripped and fell...down a cliff.'
- '&5%n&7 leapt before looking.'
- '&5%n&7 forgot to bring a parachute!'
- '&5%n&7 learned to fly...briefly...'
- '&5%n&7 felt the full effect of gravity.'
- '&5%n&7 just experienced physics in action.'
- '&5%n&7 fell to his death.'
- '&5%n&7 forgot to look out below!'
- '&5%n&7 got a little too close to the edge!'
- '&5%n&7, gravity is calling your name!'
- '&5%n&7 face planted into the ground!'
- '&5%n&7 yells, "Geronimo!"....*thud*'
- '&7What goes up must come down, right &5%n?'

drowning:
- '&5%n&7 drowned.'
- '&5%n&7 become one with the ocean!'
- '&5%n&7 sunk to the bottom of the ocean.'
- '&5%n&7 went diving but forgot the diving gear!'
- '&5%n&7 needs swimming lessons.'
- '&5%n''s&7 lungs have been replaced with H2O.'
- '&5%n&7 forgot to come up for air!'
- '&5%n&7 is swimming with the fishes!'
- '&5%n&7 had a surfing accident!'
- '&5%n&7 tried to walk on water.'
- '&5%n&7 set a record for holding breath under water.'

fire:
- '&5%n&7 burned to death.'
- '&5%n&7 was set on fire!'
- '&5%n&7 is toast! Literally...'
- '&5%n&7 just got barbequed!'
- '&5%n&7 forgot to stop, drop, and roll!'
- '&5%n&7 is extra-crispy!'
- '&5%n&7 spontaneously combusted!'
- '&5%n&7 put his hands in the toaster!'
- '&5%n&7 just got burned!'

fire_tick:
- '&5%n&7 burned to death.'
- '&5%n&7 was set on fire!'
- '&5%n&7 is toast! Literally...'
- '&5%n&7 just got barbequed!'
- '&5%n&7 forgot to stop, drop, and roll!'
- '&5%n&7 likes it extra-crispy!'
- '&5%n&7 spontaneously combusted!'
- '&5%n&7 put his hands in the toaster!'
- '&5%n&7 just got burned!'

lava:
- '&5%n&7 became obsidian.'
- '&5%n&7 was caught in an active volcanic eruption!'
- '&5%n&7 tried to swim in a pool of lava.'
- '&5%n&7 was killed by a lava eruption!'
- '&5%n&7 was forged into obsidian by molten lava.'
- '&5%n&7 took a dip in the wrong kind of pool!'
- '&5%n&7 found out how to encase himself in carbonite.'
- '&5%n&7! the floor is lava! The floor is lava!'

creeper:
- '&5%n&7 was creeper bombed!'
- '&7A creeper exploded on &5%n&7!'
- '&7A creeper snuck up on &5%n&7!'
- '&7A creeper tried to make love with &5%n&7...mmm.'
- '&5%n&7 just got the KiSSssss of death!'
- '&5%n&7 tried to hug a creeper!'
- '&5%n&7 is frowning like a creeper now!'

skeleton:
- '&7A skeleton shot &5%n&7 to death!'
- '&5%n&7 was on the wrong end of the bow. '
- '&5%n&7 had a skeleton in the closet...'
- '&5%n&7! strafe the arrows! Strafe the arrows!'
- '&7A skeleton just got a head shot on &5%n&7!'

spider:
- '&5%n&7 is all webbed up.'
- '&5%n&7 got trampled by arachnids!'
- '&5%n&7 got jumped by a spidah!'
- 'Spiders just climbed all over &5%n&7!'
- '&5%n&7 forgot spiders could climb!'

zombie:
- '&5%n&7 was punched to death by zombies!'
- '&5%n&7 was bitten by a zombie!'
- '&5%n&7 fell to the hunger of the horde!'
- '&5%n&7 Hasn''t played enough L4D2!'
- '&5%n&7 couldn''t run faster than the zombie!'

pvp:
- '&f%a&7 killed &5%n&7 using a(n) &3%i&7!'
- '&f%a&7 slays &5%n&7 with a &3%i&7!'
- '&f%a&7 hunts &5%n&7 down with a &3%i&7!'
- '&5%n&7 was killed by a &3%i&7 wielding &f%a&7!'
- '&f%a&7 leaves &5%n&7 a bloody mess!'
- '&f%a&7 uses a &3%i&7 to end &5%n''s&7 life!'
- '&5%n&7 collapses due to &3%i&7 attacks from &f%a&7!'
- '&5%n&7 is now a bloody mess thanks to &f%a''s&7 &3%i&7!'
- '&f%a&7 beats &5%n&7 with a &3%i&7!'
- '&5%n&7 was killed by &f%a''s&7 &3%i&7 attack!'
- '&f%a&7 defeats &5%n&7 with a &3%i&7 attack!'
- '&f%a&7 raises a &3%i&7 and puts and end to &5%n''s&7 life!'
- '&f%a&7 took out &5%n&7 with a &3%i&7!'
- '&5%n&7 was victimized by &f%a''s&7 &3%i&7!'
- '&5%n&7 was eliminated by &f%a''s&7 &3%i&7!'
- '&f%a&7 executes &5%n&7 with a &3%i&7!'
- '&f%a&7 finishes &5%n&7 with a &3%i&7!'
- '&f%a''s&7 &3%i&7 has claimed &5%n&7 as another victim!'
- '&5%n&7 lost a savage duel to &f%a&7!'
- '&f%a&7 has beaten &5%n&7 to a pulp!'
- '&f%a&7 pwns &5%n&7 in a vicious duel!'
- '&7Score &f%a&7 1 - &5%n&7 0!'
- '&f%a&7 has defeated &5%n&7 in battle!'
- '&5%n&7 was slain by &f%a&7!'
- '&f%a&7 emerges victorious in a duel with &5%n&7!'
- '&5%n&7 was pwned by &f%a&7!'
- '&5%n&7 was killed by &f%a&7!'
- '&5%n&7 was dominated by &f%a&7!'
- '&5%n&7 was fragged by &f%a&7!'
- '&5%n&7 needs more practice and was killed by &f%a&7!'
- '&5%n&7 was beheaded by &f%a&7!'

pvp-fists:
- '&f%a&7 pummeled &5%n&7 to death'
- '&f%a&7 crusted &5%n&7 with their bare hands'

pvp-tamed:
- '&5%n&7 was mauled by &f%a''s&7 &3%i'
- '&5%n''s&7 hand was bitten by &f%a''s&7 &3%i'

block_explosion:
- '&7Careful &5%n&7, TNT goes boom!'
- '&5%n&7 was last seen playing with dynamite.'
- '&5%n&7 exploded into a million pieces!'
- '&5%n&7 cut the wrong wire!'
- '&5%n&7 left his (bloody) mark on the world.'
- '&5%n&7 attempted to exterminate gophers with dynamite!'
- '&5%n&7 played land mine hop scotch!'
- '&5%n&7 stuck his head in a microwave!'

contact:
- '&5%n&7 got a little too close to a cactus!'
- '&5%n&7 tried to hug a cactus!'
- '&5%n&7 needs to be more careful around cactuses!'
- '&5%n&7 felt the wrath of Cactus Jack!'
- '&5%n&7 learned the result of rubbing a cactus!'
- '&5%n&7 died from cactus injuries!'
- '&5%n&7 poked himself with a cactus...and died.'
- '&5%n&7 ran into some pointy green stuff that wasn''t grass.'
- '&5%n&7 was distracted by a tumble weed and died by cactus.'

ghast:
- '&5%n&7 was blown to bits by a ghast.'
- '&7Those aren''t babies you hear, &5%n&7!'
- '&5%n&7 was killed by a ghostly hadouken!'
- '&5%n&7 just got exploded by a fireball!'
- '&5%n&7 got too comfy in the Nether!'

slime:
- '&7A slime found &5%n&7. The slime won.'
- '&5%n&7 wanted to play with slime. The slime wasn''t happy.'

suffocation:
- '&5%n&7 suffocated.'
- '&5%n&7 was looking up while digging!'
- '&5%n&7 choked to death on earth!'
- '&5%n&7 choked on a ham sandwich'

pigzombie:
- '&5%n&7 lost a fight against a zombie pig.'
- '&5%n&7, touching a zombie pig is never a good idea.'
- '&5%n&7 looked at a pigzombie the wrong way.'

void:
- '&5%n&7 died in The Void.'

wolf:
- '&5%n&7 became a wolf''s lunch.'

lightning:
- '&5%n&7 was struck down by Zeus'' bolt.'

unknown:
- '&5%n&7 died from unknown causes.'
- '&5%n&7 imploded into nothingness'
- '&5%n&7 was vaporized'
- '&5%n&7 died from explosive diarrhea'
- '&5%n&7 was killed by Chuck Norris'
- '&5%n&7 was running with scissors...now he runs no more'
- '&5%n&7 was hit by a falling piano'
- '&5%n&7 was assasinated by a shuriken headshot from the shadow'
- '&5%n&7 was barrel rolling...and died'
- '&5%n&7 was killed by Cthulhu'
- '&5%n&7 forgot to wear his spacesuit'
- '&5%n&7 choked on a ham sandwich'
- '&5%n&7 died at the hands of ninja assassins'

suicide:
- '&5%n&7 took matters into his own hands.'

starvation:
- '&5%n&7 did forget to eat his lunch.'
- '&5%n&7 didn''t find the next Burger.'
- '&5%n&7 became a skeleton.'

enderman:
- '&5%n&7 looked at a enderman the wrong way.'
- '&7An enderman pulled &5%n&7 leg..... off!'

cavespider:
- '&5%n&7 will never sing itsybitsyspider again.'
- '&5%n&7 is all webbed up.'
- '&5%n&7 was trampled by arachnids!'
- '&5%n&7 was jumped by a spidah!'
- 'Spiders just climbed all over &5%n&7!'
- '&5%n&7 forgot spiders could climb!'

silverfish:
- '&5%n&7 was killed by a silverfish!'
- '&5%n''s&7 knees were capped by a silverfish!'

giant:
- '&5%n&7 was stomped by a giant!'
- '&5%n&7 was flattened by a giant!'

blaze:
- '&5%n&7 was killed by a blaze!'

enderdragon:
- '&5%n&7 was killed by a dragon!'

dispenser:
- '&5%n&7 fell victim to a trap!'

poison:
- '&5%n&7 dropped too much acid!'
- '&5%n&7 died from food poisoning!'

magic:
- '&5%n&7 fell victim to a curse!'

iron-golem:
- '&5%n&7 messed with the wrong giant!'

# ----- Streaks

# format <#of kills> <text to display> %n = player getting the message (in this case, the one on a killstreak).

killstreak:
-  '5:&cKilling Spree! &7[5 kill streak for &f%n&7]'
- '10:&cRampage! &7[10 kill streak for &f%n&7]'
- '15:&cDominating! &7[15 kill streak for &f%n&7]'
- '20:&cUnstoppable! &7[20 kill streak for &f%n&7]'
- '25:&cGodlike! &7[25 kill streak for &f%n]'
- '30:&cWicked Sick! &7[30 kill streak for &f%n&7]'

# format <#of kills> <text to display> %n = player getting the message (in this case, the one on a deathstreak).

deathstreak:
-  '5:&5%n&c has died like, 5 times in a row.'
- '10:&5%n&c needs to craft a sword or something.'
- '15:&5%n&c needs to defend himself better.'
- '20:&5%n&c is dead more than alive.'
- '25:&5%n&c is just plain pathetic.'
- '30:&5%n&c wants to read all the death streak messages.'

multikill:
- '2:&cDouble Kill!'
- '3:&cHat Trick!'
- '4:&cMulti Kill!'
- '5:&cCombo Whore!'
- '6:&cMega Kill!'
- '7:&cUltra Kill!'
- '8:&cMonster Kill!'
- '9:&cLudicrous Kill!'
- '10:&cHoly S**t!'

sounds:
    url: 'https://raw.github.com/mung3r/DeathTpPlus/master/resources/sounds/'
    format: '.ogg'
    killstreaks: 
    - '5:killingspree'
    - '10:rampage'
    - '15:dominating'
    - '20:unstoppable'
    - '25:godlike'
    - '30:wickedsick'
    multikills:
    - '2:doublekill'
    - '3:hattrick'
    - '4:multikill'
    - '5:combowhore'
    - '6:megakill'
    - '7:ultrakill'
    - '8:monsterkill'
    - '9:ludicrouskill'
    - '10:holyshit'